export const LOGIN_LOGIN_BEGIN = 'LOGIN_LOGIN_BEGIN';
export const LOGIN_LOGIN_SUCCESS = 'LOGIN_LOGIN_SUCCESS';
export const LOGIN_LOGIN_FAILURE = 'LOGIN_LOGIN_FAILURE';
export const LOGIN_LOGIN_DISMISS_ERROR = 'LOGIN_LOGIN_DISMISS_ERROR';
export const LOGIN_LOGOUT_BEGIN = 'LOGIN_LOGOUT_BEGIN';
export const LOGIN_LOGOUT_SUCCESS = 'LOGIN_LOGOUT_SUCCESS';
export const LOGIN_LOGOUT_FAILURE = 'LOGIN_LOGOUT_FAILURE';
export const LOGIN_LOGOUT_DISMISS_ERROR = 'LOGIN_LOGOUT_DISMISS_ERROR';
